#!/usr/bin/env bash
# Build the WASM static archives we link against:
#   - libleanrt.a from lean4's src/runtime cpp files
#   - libInit.a from lean4/stage0/stdlib/Init*.c (pre-generated, no `lean` needed)
#   - libStd.a  from lean4/stage0/stdlib/Std*.c  (pre-generated, no `lean` needed)
#   - libgmp.a  from gmp source via emconfigure / emmake
#
# We do NOT build the lean compiler itself. The `stage0/stdlib/*.c` files in
# the lean4 source are exactly the elaborated-then-codegen'd output of `lean`
# applied to Init/Std .lean source — the bootstrap output. We just compile
# them with em++ to produce WASM object files.
#
# Outputs:
#   deps/lean-wasm/lib/{libleanrt,libInit,libStd}.a
#   deps/gmp-wasm/lib/libgmp.a

set -euo pipefail

WASM_BUILD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPS_DIR="$WASM_BUILD_DIR/deps"
LEAN4_SRC="$DEPS_DIR/lean4"
GMP_VERSION="${GMP_VERSION:-6.3.0}"
GMP_SRC="$DEPS_DIR/gmp-${GMP_VERSION}"
LIBUV_SRC="$DEPS_DIR/libuv"
LEAN_WASM_OUT="$DEPS_DIR/lean-wasm"
GMP_WASM_OUT="$DEPS_DIR/gmp-wasm"
LIBUV_WASM_OUT="$DEPS_DIR/libuv-wasm"
LIBUV_PATCH="$WASM_BUILD_DIR/patches/libuv-emscripten.patch"
LEAN4_THREAD_PATCH="$WASM_BUILD_DIR/patches/lean4-emscripten-thread.patch"

# Object files land here so we can resume incrementally.
OBJ_DIR="$WASM_BUILD_DIR/build/wasm-deps"
RUNTIME_OBJ="$OBJ_DIR/runtime"
INIT_OBJ="$OBJ_DIR/Init"
STD_OBJ="$OBJ_DIR/Std"
GEN_INC="$OBJ_DIR/gen-include"  # holds generated config.h + copied version.h

# ---- Preflight ---------------------------------------------------------------

# emsdk tools — needed for compiling/linking against WASM target
emsdk_missing=""
for tool in em++ emar emconfigure emmake emcmake; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    emsdk_missing="$emsdk_missing $tool"
  fi
done
if [[ -n "$emsdk_missing" ]]; then
  echo "ERROR: missing emsdk tools:$emsdk_missing" >&2
  echo "       Activate emsdk: source <emsdk>/emsdk_env.sh" >&2
  exit 1
fi

# Other tools we shell out to
host_missing=""
for tool in lean git cmake make; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    host_missing="$host_missing $tool"
  fi
done
if [[ -n "$host_missing" ]]; then
  echo "ERROR: missing host tools:$host_missing" >&2
  echo "       Install via your package manager (e.g. 'brew install cmake')." >&2
  exit 1
fi

[[ -d "$LEAN4_SRC" ]]  || { echo "ERROR: $LEAN4_SRC missing — run 'make setup'." >&2; exit 1; }
[[ -d "$GMP_SRC" ]]    || { echo "ERROR: $GMP_SRC missing — run 'make setup'." >&2; exit 1; }
[[ -d "$LIBUV_SRC" ]]  || { echo "ERROR: $LIBUV_SRC missing — run 'make setup'." >&2; exit 1; }
[[ -f "$LIBUV_PATCH" ]]        || { echo "ERROR: missing patch file $LIBUV_PATCH" >&2; exit 1; }
[[ -f "$LEAN4_THREAD_PATCH" ]] || { echo "ERROR: missing patch file $LEAN4_THREAD_PATCH" >&2; exit 1; }

# Cross-platform CPU count
if command -v sysctl >/dev/null 2>&1; then
  JOBS=$(sysctl -n hw.logicalcpu)
elif command -v nproc >/dev/null 2>&1; then
  JOBS=$(nproc)
else
  JOBS=4
fi

mkdir -p "$RUNTIME_OBJ" "$INIT_OBJ" "$STD_OBJ" "$LEAN_WASM_OUT/lib" "$GEN_INC/lean"

# Generate the headers CMake would have produced. We're building without
# mimalloc/small-allocator/lazy-rc. We also need version.h, which is the same
# constants as in the native toolchain — copy it.
cat > "$GEN_INC/lean/config.h" <<'EOF'
#pragma once
#include <lean/version.h>

#define LEAN_IS_STAGE0 0
EOF
cp "$(lean --print-prefix)/include/lean/version.h" "$GEN_INC/lean/version.h"

# githash.h is normally generated by CMake from the lean4 git rev. Lift the
# real SHA from the cloned repo.
LEAN_SHA="$(git -C "$LEAN4_SRC" rev-parse HEAD 2>/dev/null || echo unknown)"
cat > "$GEN_INC/githash.h" <<EOF
// Generated by build-deps.sh
#define LEAN_GITHASH "$LEAN_SHA"
EOF

# Common flags. -O2 is a sane default; bump to -O3 if you care more about
# runtime than build time.
#
# Note: NO -fno-exceptions. Lean's runtime uses `throw unreachable_reached()`
# in places, which -fno-exceptions would forbid at compile time. Emscripten's
# default behavior at -O1+ is to skip emitting catch blocks (exceptions
# terminate the program rather than being caught) — that's the right model
# here, and it gives us most of the size/speed win.
#
# $GEN_INC comes first so our generated config.h wins over anything else.
CXX_COMMON="-O2 -std=c++20 -fvisibility=hidden \
  -DLEAN_BUILD_FOR_RELEASE \
  -DLEAN_EMSCRIPTEN \
  -DLEAN_MULTI_THREAD \
  -I$GEN_INC \
  -I$LEAN4_SRC/src/include \
  -I$LEAN4_SRC/src \
  -I$GMP_WASM_OUT/include \
  -I$LIBUV_WASM_OUT/include"

# ---- 1. Build GMP for WASM ---------------------------------------------------

if [[ -f "$GMP_WASM_OUT/lib/libgmp.a" ]]; then
  echo "==> GMP already built ($GMP_WASM_OUT/lib/libgmp.a); skipping."
else
  echo "==> Building GMP for WASM (this is the slow step — go grab coffee)"
  cd "$GMP_SRC"
  if [[ ! -f Makefile ]]; then
    # HOST_CC must be a native compiler — autoconf builds tiny helper programs
    # during configure that have to run on the build machine, not in WASM.
    # /usr/bin/cc on macOS resolves to Apple clang via xcrun.
    emconfigure ./configure \
      --host=none \
      --disable-assembly \
      --disable-shared \
      --enable-static \
      --prefix="$GMP_WASM_OUT" \
      HOST_CC=/usr/bin/cc \
      CC_FOR_BUILD=/usr/bin/cc
  fi
  emmake make -j"$JOBS"
  emmake make install
fi

# ---- 2. Build libuv for WASM -------------------------------------------------
#
# Lean's runtime includes libuv.h transitively, so we need the headers and the
# archive. We follow lean4's own recipe (src/CMakeLists.txt): clone v1.48.0,
# apply a tiny patch that adds src/unix/no-proctitle.c to the build for
# Emscripten, then `emcmake` + `emmake` to produce libuv.a.
#
# Several libuv symbols stay undefined under Emscripten (uv__io_poll, etc.) —
# that's expected; they get dead-stripped at the final link as long as our
# app doesn't reach them. Our demo doesn't.

if [[ -f "$LIBUV_WASM_OUT/lib/libuv.a" ]]; then
  echo "==> libuv already built ($LIBUV_WASM_OUT/lib/libuv.a); skipping."
else
  echo "==> Building libuv for WASM"

  # Apply patch idempotently. `git apply --check` is true if the patch hasn't
  # been applied yet; `--reverse --check` is true if it's already applied.
  cd "$LIBUV_SRC"
  if git apply --reverse --check "$LIBUV_PATCH" 2>/dev/null; then
    echo "    patch already applied"
  else
    git apply "$LIBUV_PATCH"
    echo "    applied $LIBUV_PATCH"
  fi

  mkdir -p "$LIBUV_SRC/build-wasm"
  cd "$LIBUV_SRC/build-wasm"
  if [[ ! -f CMakeCache.txt ]]; then
    emcmake cmake .. \
      -DCMAKE_BUILD_TYPE=Release \
      -DLIBUV_BUILD_TESTS=OFF \
      -DLIBUV_BUILD_SHARED=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  fi
  emmake make -j"$JOBS"

  # Stage outputs into LIBUV_WASM_OUT
  mkdir -p "$LIBUV_WASM_OUT/lib" "$LIBUV_WASM_OUT/include"
  cp "$LIBUV_SRC/build-wasm/libuv.a" "$LIBUV_WASM_OUT/lib/libuv.a"
  cp -R "$LIBUV_SRC/include/." "$LIBUV_WASM_OUT/include/"
  echo "    -> $LIBUV_WASM_OUT/lib/libuv.a"
fi

# ---- 3. Compile Lean runtime (lean4/src/runtime/*.cpp) -----------------------
#
# Now that libuv headers are available, we include all the runtime cpp files,
# matching lean4's RUNTIME_OBJS list in src/runtime/CMakeLists.txt.

RUNTIME_CPP=(
  debug.cpp thread.cpp mpz.cpp utf8.cpp object.cpp apply.cpp
  exception.cpp interrupt.cpp memory.cpp stackinfo.cpp compact.cpp
  init_module.cpp io.cpp hash.cpp byteslice.cpp platform.cpp
  alloc.cpp allocprof.cpp sharecommon.cpp stack_overflow.cpp
  process.cpp object_ref.cpp mpn.cpp mutex.cpp
  libuv.cpp
  # Skipping uv/*.cpp: under LEAN_EMSCRIPTEN, libuv.cpp's `initialize_libuv()`
  # is empty and doesn't pull in any uv/* symbols, and lean4's emscripten
  # stubs in those files have a return-type mismatch in lean_uv_event_loop_alive
  # (declared uint8_t in the header, defined as lean_obj_res). Drop them and
  # rely on the linker to dead-strip any references from Init/Std.
)

LIBLEANRT="$LEAN_WASM_OUT/lib/libleanrt.a"
if [[ -f "$LIBLEANRT" ]]; then
  echo "==> $LIBLEANRT already built; skipping."
else
  # Apply lean4 thread patch idempotently (lthread runs synchronously under
  # LEAN_EMSCRIPTEN; without -pthread, pthread_create would throw at startup).
  cd "$LEAN4_SRC"
  if git apply --reverse --check "$LEAN4_THREAD_PATCH" 2>/dev/null; then
    echo "==> lean4 thread patch already applied"
  else
    git apply "$LEAN4_THREAD_PATCH"
    echo "==> applied $LEAN4_THREAD_PATCH"
  fi
  cd "$WASM_BUILD_DIR"

  echo "==> Compiling ${#RUNTIME_CPP[@]} runtime cpp files"
  for f in "${RUNTIME_CPP[@]}"; do
    src="$LEAN4_SRC/src/runtime/$f"
    obj="$RUNTIME_OBJ/${f%.cpp}.o"
    mkdir -p "$(dirname "$obj")"  # for uv/*.cpp
    if [[ "$obj" -nt "$src" ]]; then continue; fi  # incremental
    printf "    %s\n" "$f"
    em++ $CXX_COMMON -c "$src" -o "$obj"
  done
  # Recursive find — uv/*.o lives in a subdir
  find "$RUNTIME_OBJ" -name "*.o" -print0 | xargs -0 emar rcs "$LIBLEANRT"
  echo "    -> $LIBLEANRT"
fi

# ---- 3. Compile stage0 Init/*.c and Std/*.c ---------------------------------
#
# Lean's generated .c files use `extern "C" {}` blocks (i.e., they're C++).
# Compile with em++ accordingly. We compile the whole forest; the linker
# dead-strips unused symbols when the archives are linked into the final exe.

# Helper: compile a single .c (Lean codegen output) into a .o
compile_lean_c() {
  local src="$1"
  local obj="$2"
  if [[ "$obj" -nt "$src" ]]; then return 0; fi
  em++ $CXX_COMMON -x c++ -c "$src" -o "$obj"
}
export -f compile_lean_c
export CXX_COMMON

# Build a (src, obj) plan for Init and Std
build_archive() {
  local libname="$1"     # "Init" or "Std"
  local objdir="$2"
  local outpath="$LEAN_WASM_OUT/lib/lib${libname}.a"

  if [[ -f "$outpath" ]]; then
    echo "==> $outpath already built; skipping."
    return 0
  fi

  local top_c="$LEAN4_SRC/stage0/stdlib/${libname}.c"
  local sub_root="$LEAN4_SRC/stage0/stdlib/${libname}"

  if [[ ! -f "$top_c" ]]; then
    echo "ERROR: missing $top_c" >&2
    exit 1
  fi

  # Mirror the source tree layout under objdir so paths don't collide
  echo "==> Compiling lib${libname}.a from stage0/stdlib/${libname}*"
  local count=0
  for src in "$top_c" $(find "$sub_root" -name "*.c" 2>/dev/null); do
    rel="${src#$LEAN4_SRC/stage0/stdlib/}"
    obj="$objdir/${rel%.c}.o"
    mkdir -p "$(dirname "$obj")"
    compile_lean_c "$src" "$obj"
    count=$((count+1))
    if (( count % 50 == 0 )); then
      printf "    [%4d compiled]\n" "$count"
    fi
  done
  echo "    [$count compiled total]"
  # Use find to glob recursively (bash globstar may not be on)
  find "$objdir" -name "*.o" -print0 | xargs -0 emar rcs "$outpath"
  echo "    -> $outpath"
}

build_archive Init "$INIT_OBJ"
build_archive Std  "$STD_OBJ"

# ---- Done --------------------------------------------------------------------

cat <<EOF

==> WASM dependencies built:
    $LEAN_WASM_OUT/lib/libleanrt.a
    $LEAN_WASM_OUT/lib/libInit.a
    $LEAN_WASM_OUT/lib/libStd.a
    $GMP_WASM_OUT/lib/libgmp.a

Now run \`make\` from $WASM_BUILD_DIR to link the demo.
EOF
